### ISSUE TITLE
Standardize logging & error handling

### ISSUE THREAD

**Issue by yqszxx** [yqszxx/oreo-box#4]
1. Remove dependency to `github.com/Sirupsen/logrus`.
2. Only use `log.Print` and friends to print.
3. All functions that might fail must have an `error` type return value as last return value.
4. All caller to funtions that returns `error` must explicitly ignore the error or handle it properly (ie. return it to caller).

Leave comments to specify files / functions you are editing to prevent potential merge conflicts.
```go
if err := SomeFunction(); err != nil {
    return err
}
```

**Comment by yqszxx** [comment]
- `run.go`
- `exec.go`
- `container/container_process.go`
- `container/init.go`
- `main_command.go : runCommand.Action`
- `main_command.go : initCommand.Action`
- `main_command.go : execCommand.Action`

**Comment by dk-kristy** [comment]
- `cgroups/*`

**Comment by ZongZheng300** [comment]
- `container/volume.go`
- `container/init.go`

**Comment by ZongZheng300** [comment]
- `stop.go`

**Comment by ZongZheng300** [comment]
- `container/volume.go`
- `container/init.go`
- `stop.go`
- `main_command.go : stopCommand.Action`
- `main_command.go : removeCommand.Action`

**Comment by zmuzhi1010** [comment]
- `network/*`
